### ISSUE TITLE
Not enough space on device /dev/sda in WSL

### ISSUE THREAD

**Issue by yanecc** [nxtgencat/ChromeOS#1]
```
sda    8:0    0 388.5M  1 disk
sdb    8:16   0     4G  0 disk [SWAP]
sdc    8:32   0     1T  0 disk /mnt/wslg/distro

----------------------------------------

- Do you want to (i)nstall Chrome OS, (c)reate an ISO, or (q)uit ? : i

- Do you want to install in the default location /sda? [ (y)es / (n)o / cust(o)m ]: y

- Installing Chrome OS...
Not enough space on device /dev/sda

- Chrome OS Not Installed.
```

**Comment by nxtgencat** [comment]
The space on /dev/sda is only 388.5 MB, which is insufficient for installing an operating system like Chrome OS.

**Comment by yanecc** [comment]
So, how could I install ChromeOS in WSL via the script?
Could u please provide more detailed explanation?

**Comment by yanecc** [comment]
> The space on /dev/sda is only 388.5 MB, which is insufficient for installing an operating system like Chrome OS.

So, how could I install ChromeOS in WSL via the script?
Could u please provide more detailed explanation?
